teams:
  cli-experimental-admins:
    description: admin access to cli-experimental
    members:
    - Liujingfang1
    - pwittrock
    - seans3
    - soltysh
    privacy: closed
    repos:
      cli-experimental: admin
  cli-experimental-maintainers:
    description: write access to cli-experimental
    members:
    - liggitt
    - Liujingfang1
    - monopole
    privacy: closed
    repos:
      cli-experimental: write
  cli-utils-admins:
    description: admin access to cli-utils
    members:
    - Liujingfang1
    - mortent
    - phanimarupaka
    - pwittrock
    - seans3
    - soltysh
    privacy: closed
    repos:
      cli-utils: admin
  cli-utils-maintainers:
    description: write access to cli-utils
    members:
    - liggitt
    - Liujingfang1
    - monopole
    privacy: closed
    repos:
      cli-utils: write
  krew-admins:
    description: admin access to krew
    members:
    - ahmetb
    - chriskim06
    - corneliusweig
    - pwittrock
    - seans3
    - soltysh
    privacy: closed
    repos:
      krew: admin
  krew-maintainers:
    description: write access to krew
    members:
    - ahmetb
    - chriskim06
    - corneliusweig
    - pwittrock
    - seans3
    - soltysh
    privacy: closed
    repos:
      krew: write
  krew-index-admins:
    description: admin access to krew-index
    members:
    - ahmetb
    - chriskim06
    - corneliusweig
    - pwittrock
    - seans3
    - soltysh
    privacy: closed
    repos:
      krew-index: admin
  krew-index-maintainers:
    description: write access to krew-index
    members:
    - ahmetb
    - chriskim06
    - corneliusweig
    - pwittrock
    - seans3
    - soltysh
    privacy: closed
    repos:
      krew-index: write
  kui-admins:
    description: admin access to kui
    members:
    - myan9
    - starpit
    privacy: closed
    repos:
      kui: admin
  kui-maintainers:
    description: write access to kui
    members:
    - eddiezane
    - mark-nc
    - myan9
    - pwittrock
    - seans3
    - soltysh
    - starpit
    privacy: closed
    repos:
      kui: admin
  kustomize-admins:
    description: ""
    members:
    - droot
    - Liujingfang1
    - monopole
    - pwittrock
    privacy: closed
    repos:
      kustomize: admin
  kustomize-maintainers:
    description: ""
    members:
    - haiyanmeng
    - mortent
    - natasha41575
    - phanimarupaka
    - pwittrock
    - Shell32-Natsu
    privacy: closed
    repos:
      kustomize: maintain
