teams:
  execution-hook-admins:
    description: Admin access to execution-hook repo
    members:
    - kow3ns
    - liyinan926
    privacy: closed
    repos:
      execution-hook: admin
  execution-hook-maintainers:
    description: Write access to execution-hook repo
    members:
    - jingxu97
    - kow3ns
    - liyinan926
    - xing-yang
    privacy: closed
    repos:
      execution-hook: write
