teams:
  aws-ebs-csi-driver-admins:
    description: ""
    members:
    - leakingtapan
    - wongma7
    privacy: closed
    repos:
      aws-ebs-csi-driver: admin
  aws-ebs-csi-driver-maintainers:
    description: ""
    members:
    - AndyXiangLi
    - bertinatto
    - gnufied
    - jsafrane
    - leakingtapan
    - wongma7
    privacy: closed
    repos:
      aws-ebs-csi-driver: write
  aws-encryption-provider-admins:
    description: admin access to aws_encryption-provider repo
    members:
    - justinsb
    - robinpercy
    privacy: closed
    repos:
      aws-encryption-provider: admin
  aws-encryption-provider-maintainers:
    description: write access to aws_encryption-provider
    members:
    - justinsb
    - robinpercy
    privacy: closed
    repos:
      aws-encryption-provider: write
  aws-fsx-csi-driver-admins:
    description: admin access to aws-fsx-csi-driver
    members:
    - d-nishi
    - justinsb
    - leakingtapan
    privacy: closed
    repos:
      aws-fsx-csi-driver: admin
  aws-fsx-csi-driver-maintainers:
    description: write access to aws-fsx-csi-driver
    members:
    - d-nishi
    - jsafrane
    - justinsb
    - leakingtapan
    - wongma7
    privacy: closed
    repos:
      aws-fsx-csi-driver: write
  aws-efs-csi-driver-admins:
    description: admin access to aws-efs-csi-driver
    members:
    - d-nishi
    - justinsb
    - leakingtapan
    privacy: closed
    repos:
      aws-efs-csi-driver: admin
  aws-efs-csi-driver-maintainers:
    description: write access to aws-efs-csi-driver
    members:
    - d-nishi
    - jsafrane
    - justinsb
    - leakingtapan
    - wongma7
    privacy: closed
    repos:
      aws-efs-csi-driver: write
