teams:
  cluster-proportional-autoscaler-admins:
    description: Admin access to the cluster-proportional-autoscaler repo
    members:
    - bowei
    - MrHohn
    - thockin
    privacy: closed
    repos:
      cluster-proportional-autoscaler: admin
  cluster-proportional-autoscaler-maintainers:
    description: Write access to the cluster-proportional-autoscaler repo
    members:
    - bowei
    - MrHohn
    - thockin
    privacy: closed
    repos:
      cluster-proportional-autoscaler: write
  cluster-proportional-vertical-autoscaler-admins:
    description: Admin access to the cluster-proportional-autoscaler repo
    members:
    - bowei
    - MrHohn
    - thockin
    privacy: closed
    repos:
      cluster-proportional-vertical-autoscaler: admin
  cluster-proportional-vertical-autoscaler-maintainers:
    description: Admin access to the cluster-proportional-autoscaler repo
    members:
    - bowei
    - MrHohn
    - thockin
    privacy: closed
    repos:
      cluster-proportional-vertical-autoscaler: write
  ip-masq-agent-admins:
    description: Admin access to the ip-masq-agent repo
    members:
    - bowei
    - MrHohn
    privacy: closed
    previously:
    - admins-ip-masq-agent
    repos:
      ip-masq-agent: admin
  ip-masq-agent-maintainers:
    description: Write access to the ip-masq-agent repo
    members:
    - bowei
    - MrHohn
    privacy: closed
    previously:
    - maintainers-ip-masq-agent
    repos:
      ip-masq-agent: write
  external-dns-admins:
    description: Admin access to the external-dns repo
    members:
    - hjacobs
    - linki
    - njuettner
    - Raffo
    privacy: closed
    previously:
    - admins-external-dns
    repos:
      external-dns: admin
  external-dns-maintainers:
    description: Write access to the external-dns repo
    members:
    - hjacobs
    - linki
    - njuettner
    - Raffo
    privacy: closed
    previously:
    - maintainers-external-dns
    repos:
      external-dns: write
  ingress-controller-conformance-admins:
    description: Admin access to the ingress-controller-conformance repo
    members:
    - alexgervais
    - bowei
    - thockin
    privacy: closed
    previously:
    - admins-ingress-controller-conformance
    repos:
      ingress-controller-conformance: admin
  ingress-controller-conformance-maintainers:
    description: Write access to the ingress-controller-conformance repo
    members:
    - alexgervais
    - bowei
    - thockin
    privacy: closed
    previously:
    - maintainers-ingress-controller-conformance
    repos:
      ingress-controller-conformance: write
  iptables-wrappers-admins:
    description: Admin access to the iptables-wrappers repo
    members:
    - caseydavenport
    - danwinship
    - dcbw
    - thockin
    privacy: closed
    repos:
      iptables-wrappers: admin
  iptables-wrappers-maintainers:
    description: Write access to the iptables-wrappers repo
    members:
    - caseydavenport
    - danwinship
    - dcbw
    - thockin
    privacy: closed
    repos:
      iptables-wrappers: write
  gateway-api-admins:
    description: Admin access to the gateway-api repo
    members:
    - bowei
    - thockin
    privacy: closed
    previously:
    - service-apis-admins
    repos:
      gateway-api: admin
  gateway-api-maintainers:
    description: Write access to the gateway-api repo
    members:
    - bowei
    - danehans
    - hbagdi
    - jpeach
    - robscott
    - thockin
    privacy: closed
    previously:
    - service-apis-maintainers
    - service-apis-amintainers
    repos:
      gateway-api: write
  kpng-admins:
    description: Admin access to the kpng repo
    members:
    - mcluseau
    - thockin
    privacy: closed
    repos:
      kpng: admin
