teams:
  windows-gmsa-admins:
    description: Admin access to windows-gmsa repo
    members:
    - ddebroy
    - jayunit100
    - jsturtevant
    - marosset
    privacy: closed
    repos:
      windows-gmsa: admin
  windows-gmsa-maintainers:
    description: Write access to windows-gmsa repo
    members:
    - ddebroy
    - jayunit100
    - jsturtevant
    - marosset
    privacy: closed
    repos:
      windows-gmsa: write
  sig-windows-samples-admins:
    description: Admin access to sig-windows-samples repo
    members:
    - ddebroy
    - jayunit100
    - jsturtevant
    - marosset
    privacy: closed
    previously:
    - sig-windows-examples-admins
    repos:
      sig-windows-samples: admin
  sig-windows-samples-maintainers:
    description: Write access to sig-windows-samples repo
    members:
    - ddebroy
    - jayunit100
    - jsturtevant
    - marosset
    privacy: closed
    previously:
    - sig-windows-examples-maintainers
    repos:
      sig-windows-samples: write
  sig-windows-tools-admins:
    description: Admin access to sig-windows-tools repo
    members:
    - ddebroy
    - jayunit100
    - jsturtevant
    - marosset
    privacy: closed
    repos:
      sig-windows-tools: admin
  sig-windows-tools-maintainers:
    description: Write access to sig-windows-tools repo
    members:
    - ddebroy
    - jayunit100
    - jsturtevant
    - marosset
    privacy: closed
    repos:
      sig-windows-tools: write
  windows-testing-admins:
    description: Admin access to the windows-testing repo
    members:
    - adelina-t
    - ddebroy
    - jayunit100
    - jsturtevant
    - marosset
    privacy: closed
    repos:
      windows-testing: admin
  windows-testing-maintainers:
    description: Write access to the windows-testing repo
    members:
    - adelina-t
    - ddebroy
    - jayunit100
    - jsturtevant
    - marosset
    privacy: closed
    repos:
      windows-testing: write
