teams:
  cluster-api-provider-ibmcloud-admins:
    description: Admin access to cluster-api-provider-ibmcloud repo
    members:
    - gyliu513
    privacy: closed
    repos:
      cluster-api-provider-ibmcloud: admin
  cluster-api-provider-ibmcloud-maintainers:
    description: Write access to the cluster-api-provider-ibmcloud repo
    members:
    - gyliu513
    - jichenjc
    - xunpan
    privacy: closed
    repos:
      cluster-api-provider-ibmcloud: write
