teams:
  apiserver-network-proxy-admins:
    description: admin access to apiserver-network-proxy
    members:
    - andrewsykim
    - anfernee
    - caesarxuchao
    - cheftako
    - mcrute
    privacy: closed
    repos:
      apiserver-network-proxy: admin
  apiserver-network-proxy-maintainers:
    description: write access to apiserver-network-proxy
    members:
    - andrewsykim
    - anfernee
    - caesarxuchao
    - cheftako
    - mcrute
    privacy: closed
    repos:
      apiserver-network-proxy: write
  alibaba-cloud-csi-driver-admins:
   description: Admin access to alibaba-cloud-csi-driver repo
   members:
   - fredkan
   - xianlubird
   privacy: closed
   repos:
    alibaba-cloud-csi-driver: admin
  alibaba-cloud-csi-driver-maintainers:
   description: Write access to alibaba-cloud-csi-driver repo
   members:
   - fredkan
   - xianlubird
   privacy: closed
   repos:
     alibaba-cloud-csi-driver: write
  aws-iam-authenticator-admins:
   description: Admin access to the aws-iam-authenticator repo
   members:
   - m00nf1sh
   - micahhausler
   - nckturner
   - wongma7
   privacy: closed
   repos:
     aws-iam-authenticator: admin
  aws-iam-authenticator-maintainers:
   description: Write access to the aws-iam-authenticator repo
   members:
   - m00nf1sh
   - micahhausler
   - nckturner
   - wongma7
   privacy: closed
   repos:
     aws-iam-authenticator: write
  blobfuse-csi-driver-admins:
   description: Admin access to the blobfuse-csi-driver repo
   members:
   - andyzhangx
   - feiskyer
   - justaugustus
   - khenidak
   - lachie83
   privacy: closed
   repos:
     blob-csi-driver: maintain
  blobfuse-csi-driver-maintainers:
   description: Write access to the blobfuse-csi-driver repo
   members:
   - andyzhangx
   - feiskyer
   - justaugustus
   - khenidak
   - lachie83
   privacy: closed
   repos:
     blob-csi-driver: maintain
  cloud-provider-baiducloud-admins:
   description: Admin access to the cloud-provider-baiducloud repo
   members:
   - hello2mao
   - tizhou86
   - ZP-AlwaysWin
   privacy: closed
   repos:
     cloud-provider-baiducloud: admin
  cloud-provider-baiducloud-maintainers:
   description: Write access to the cloud-provider-baiducloud repo
   members:
   - hello2mao
   - tizhou86
   - ZP-AlwaysWin
   privacy: closed
   repos:
     cloud-provider-baiducloud: write
  cloud-provider-huaweicloud-admins:
   description: Admin access to the cloud-provider-huaweicloud repo
   members:
   - kevin-wangzefeng
   - RainbowMango
   privacy: closed
   repos:
     cloud-provider-huaweicloud: admin
  cloud-provider-huaweicloud-maintainers:
   description: Write access to the cloud-provider-huaweicloud repo
   members:
   - kevin-wangzefeng
   - RainbowMango
   privacy: closed
   repos:
     cloud-provider-huaweicloud: write