teams:
  service-catalog-admins:
    description: Admin access to the service-catalog repo
    members:
    - jberkhahn
    - jhvhs
    privacy: closed
    repos:
      go-open-service-broker-client: admin
      service-catalog: admin
  service-catalog-maintainers:
    description: Write access to the service-catalog repo
    members:
    - carolynvs
    - jberkhahn
    - jhvhs
    - mhbauer
    - piotrmiskiewicz
    privacy: closed
    repos:
      go-open-service-broker-client: write
      service-catalog: write
  minibroker-admins:
    description: Admin access to the minibroker repo
    members:
    - carolynvs
    - f0rmiga
    privacy: closed
    repos:
      minibroker: admin
