teams:
  contributor-tweets-admins:
    description: admin access to contributor-tweets
    maintainers:
    - cblecker
    - mrbobbytables
    - nikhita
    members:
    - castrojo
    privacy: closed
    repos:
      contributor-tweets: admin
  contributor-tweets-maintainers:
    description: write access to contributor-tweets
    maintainers:
    - cblecker
    - mrbobbytables
    - nikhita
    members:
    - castrojo
    privacy: closed
    repos:
      contributor-tweets: write
  discuss-theme-admins:
    description: admin access to the discuss-theme repo
    maintainers:
    - mrbobbytables
    members:
    - castrojo
    privacy: closed
    repos:
      discuss-theme: admin
  discuss-theme-maintainers:
    description: write access to the discuss-theme repo
    maintainers:
    - mrbobbytables
    members:
    - castrojo
    privacy: closed
    repos:
      discuss-theme: write
  slack-infra-admins:
    description: admin access to slack-infra
    members:
    - jeefy
    - Katharine
    privacy: closed
    repos:
      slack-infra: admin
