teams:
  boskos-admins:
    description: admin access to kubernetes-sigs/boksos
    members:
    - alvaroaleman
    - ixdy
    - stevekuznetsov
    privacy: closed
    repos:
      boskos: admin
  boskos-maintainers:
    description: write access to kubernetes-sigs/boksos
    members:
    - alvaroaleman
    - ixdy
    - stevekuznetsov
    privacy: closed
    repos:
      boskos: write
  e2e-framework-admins:
    description: admin access to e2e-framework
    maintainers:
    - spiffxp
    members:
    - alejandrox1
    - andrewsykim
    - BenTheElder
    privacy: closed
    repos:
      e2e-framework: admin
  e2e-framework-maintainers:
    description: write access to e2e-framework
    maintainers:
    - spiffxp
    members:
    - alejandrox1
    - andrewsykim
    - BenTheElder
    privacy: closed
    repos:
      e2e-framework: write
  kind-admins:
    description: Admin access to the kind repo
    members:
    - amwat
    - aojea
    - BenTheElder
    - munnerz
    privacy: closed
    repos:
      kind: admin
  kind-maintainers:
    description: Write access to the kind repo
    members:
    - amwat
    - aojea
    - BenTheElder
    - munnerz
    privacy: closed
    repos:
      kind: write
  kubetest2-admins:
    description: Admin access to kubetest2
    maintainers:
    - spiffxp
    members:
    - amwat
    - BenTheElder
    privacy: closed
    repos:
      kubetest2: admin
  kubetest2-maintainers:
    description: Write access to kubetest2
    maintainers:
    - spiffxp
    members:
    - amwat
    - BenTheElder
    privacy: closed
    repos:
      kubetest2: write
  k8s-gsm-tools-admins:
    description: Admin access to k8s-gsm-tools
    maintainers:
    - spiffxp
    members:
    - BenTheElder
    privacy: closed
    previously:
    - secret-sync-rotation-admins
    repos:
      k8s-gsm-tools: admin
  k8s-gsm-tools-maintainers:
    description: Write access to k8s-gsm-tools
    maintainers:
    - spiffxp
    members:
    - BenTheElder
    privacy: closed
    previously:
    - secret-sync-rotation-maintainers
    repos:
      k8s-gsm-tools: write
